[package]
    name = 'jvm'
    version = '0.1.0'
    edition = '2021'

[lib]
    crate-type = [ 'cdylib' ]

[dependencies]
    #zerocopy = '0.7.0-alpha.4'
    #classfile-parser = '0.3.6'
    gen = { path = 'gen' }
    zip = "0.6.0"
    #inkwell = { features = ["llvm12-0"] }
# TODO: add it for jit!
