[package]
    name = 'gen'
    version = '0.1.0'
    edition = '2021'

[lib]
    proc-macro = true

[dependencies]
    syn = { version ='2.0.18', features = ["full", "fold"] }
    quote = '1.0.28'
    proc-macro2 = "1.0.60"
